# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 05:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdn_controllers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sdncontroller',
            name='role',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='sdncontroller',
            name='summary',
            field=models.CharField(default='unknown', max_length=100),
        ),
    ]
