# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdn_controllers', '0002_auto_20160512_0745'),
    ]

    operations = [
        migrations.AddField(
            model_name='sdncontroller',
            name='status',
            field=models.CharField(default='unknown', max_length=50),
        ),
    ]
