# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 05:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdn_controllers', '0003_auto_20160517_0554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sdncontroller',
            name='role',
            field=models.CharField(default='unknown', max_length=200),
        ),
        migrations.AlterField(
            model_name='sdncontroller',
            name='tables',
            field=models.CharField(default='unknown', max_length=200),
        ),
    ]
