# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 00:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hypervisor',
            fields=[
                ('id', models.CharField(default='unknown', max_length=50, primary_key=True, serialize=False)),
                ('status', models.CharField(default='unknown', max_length=50)),
                ('service', models.CharField(default='unknown', max_length=50)),
                ('vcpus_used', models.CharField(default='unknown', max_length=50)),
                ('hypervisor_type', models.CharField(default='unknown', max_length=50)),
                ('local_gb_used', models.CharField(default='unknown', max_length=50)),
                ('vcpus', models.CharField(default='unknown', max_length=50)),
                ('hypervisor_hostname', models.CharField(default='unknown', max_length=50)),
                ('memory_mb_used', models.CharField(default='unknown', max_length=50)),
                ('memory_mb', models.CharField(default='unknown', max_length=50)),
                ('current_workload', models.CharField(default='unknown', max_length=50)),
                ('state', models.CharField(default='unknown', max_length=50)),
                ('host_ip', models.CharField(default='unknown', max_length=50)),
                ('cpu_info', models.CharField(default='unknown', max_length=50)),
                ('running_vms', models.CharField(default='unknown', max_length=50)),
                ('free_disk_gb', models.CharField(default='unknown', max_length=50)),
                ('hypervisor_version', models.CharField(default='unknown', max_length=50)),
                ('disk_available_least', models.CharField(default='unknown', max_length=50)),
                ('local_gb', models.CharField(default='unknown', max_length=50)),
                ('free_ram_mb', models.CharField(default='unknown', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('port_state', models.CharField(default='unknown', max_length=50)),
                ('fixed_ips', models.CharField(default='unknown', max_length=50)),
                ('mac_addr', models.CharField(default='unknown', max_length=50, primary_key=True, serialize=False)),
                ('net_id', models.CharField(default='unknown', max_length=50)),
                ('port_id', models.CharField(default='unknown', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('status', models.CharField(default='unknown', max_length=50)),
                ('subnets', models.CharField(default='unknown', max_length=50)),
                ('name', models.CharField(default='unknown', max_length=50)),
                ('provider_physical_network', models.CharField(blank=True, default='unknown', max_length=50, null=True)),
                ('router_external', models.CharField(default='unknown', max_length=50)),
                ('tenant_id', models.CharField(default='unknown', max_length=50)),
                ('admin_state_up', models.CharField(default='unknown', max_length=50)),
                ('provider_network_type', models.CharField(default='unknown', max_length=50)),
                ('port_security_enabled', models.CharField(default='unknown', max_length=50)),
                ('shared', models.CharField(default='unknown', max_length=50)),
                ('mtu', models.CharField(default='unknown', max_length=50)),
                ('id', models.CharField(default='unknown', max_length=50, primary_key=True, serialize=False)),
                ('provider_segmentation_id', models.CharField(blank=True, default='unknown', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('status', models.CharField(default='unknown', max_length=50)),
                ('binding_host_id', models.CharField(default='unknown', max_length=50)),
                ('name', models.CharField(default='unknown', max_length=50)),
                ('allowed_address_pairs', models.CharField(default='unknown', max_length=50)),
                ('admin_state_up', models.CharField(default='unknown', max_length=50)),
                ('network_id', models.CharField(default='unknown', max_length=50)),
                ('tenant_id', models.CharField(default='unknown', max_length=50)),
                ('extra_dhcp_opts', models.CharField(default='unknown', max_length=50)),
                ('mac_address', models.CharField(default='unknown', max_length=50)),
                ('binding_vif_details', models.CharField(default='unknown', max_length=50)),
                ('binding_vif_type', models.CharField(default='unknown', max_length=50)),
                ('device_owner', models.CharField(default='unknown', max_length=50)),
                ('binding_profile', models.CharField(default='unknown', max_length=50)),
                ('port_security_enabled', models.CharField(default='unknown', max_length=50)),
                ('binding_vnic_type', models.CharField(default='unknown', max_length=50)),
                ('fixed_ips', models.CharField(default='unknown', max_length=50)),
                ('id', models.CharField(default='unknown', max_length=50, primary_key=True, serialize=False)),
                ('security_groups', models.CharField(default='unknown', max_length=50)),
                ('device_id', models.CharField(default='unknown', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('addresses', models.CharField(default='unknown', max_length=50)),
                ('created', models.CharField(default='unknown', max_length=50)),
                ('flavor', models.CharField(default='unknown', max_length=50)),
                ('hostId', models.CharField(default='unknown', max_length=50)),
                ('id', models.CharField(default='unknown', max_length=50, primary_key=True, serialize=False)),
                ('image', models.CharField(default='unknown', max_length=50)),
                ('key_name', models.CharField(blank=True, default='unknown', max_length=50, null=True)),
                ('links', models.CharField(default='unknown', max_length=50)),
                ('metadata', models.CharField(default='unknown', max_length=50)),
                ('security_groups', models.CharField(default='unknown', max_length=50)),
                ('status', models.CharField(default='unknown', max_length=50)),
                ('tenant_id', models.CharField(default='unknown', max_length=50)),
                ('updated', models.CharField(default='unknown', max_length=50)),
                ('user_id', models.CharField(default='unknown', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='VIM',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('alias', models.CharField(default='', max_length=50)),
                ('project_domain_id', models.CharField(default='default', max_length=50)),
                ('user_domain_id', models.CharField(default='default', max_length=50)),
                ('project_name', models.CharField(default='admin', max_length=50)),
                ('tenant_name', models.CharField(default='admin', max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('auth_url', models.CharField(default='http://192.168.43.3:35357/v2.0', max_length=50)),
                ('version', models.CharField(choices=[('Kilo', 'Kilo'), ('Liberty', 'Liberty'), ('Mitaka', 'Mitaka')], default='Kilo', max_length=50)),
                ('status', models.CharField(default='unknown', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='server',
            name='owner_vim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openstack.VIM'),
        ),
        migrations.AddField(
            model_name='port',
            name='owner_vim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openstack.VIM'),
        ),
        migrations.AddField(
            model_name='network',
            name='owner_vim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openstack.VIM'),
        ),
        migrations.AddField(
            model_name='interface',
            name='owner_server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openstack.Server'),
        ),
        migrations.AddField(
            model_name='hypervisor',
            name='owner_vim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openstack.VIM'),
        ),
    ]
