# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 00:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OpenFlowEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('byteCount', models.CharField(default='unknown', max_length=50)),
                ('cookie', models.CharField(default='unknown', max_length=50)),
                ('durationNSeconds', models.CharField(default='unknown', max_length=50)),
                ('durationSeconds', models.CharField(default='unknown', max_length=50)),
                ('flags', models.CharField(default='unknown', max_length=50)),
                ('hardTimeoutSec', models.CharField(default='unknown', max_length=50)),
                ('idleTimeoutSec', models.CharField(default='unknown', max_length=50)),
                ('instructions', models.CharField(default='unknown', max_length=50)),
                ('match', models.CharField(default='unknown', max_length=50)),
                ('packetCount', models.CharField(default='unknown', max_length=50)),
                ('priority', models.CharField(default='unknown', max_length=50)),
                ('tableId', models.CharField(default='unknown', max_length=50)),
                ('version', models.CharField(default='unknown', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OpenFlowPort',
            fields=[
                ('id', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('version', models.CharField(default='unknown', max_length=50)),
                ('collisions', models.CharField(default='unknown', max_length=50)),
                ('durationNsec', models.CharField(default='unknown', max_length=50)),
                ('durationSec', models.CharField(default='unknown', max_length=50)),
                ('portNumber', models.CharField(default='unknown', max_length=50)),
                ('receiveBytes', models.CharField(default='unknown', max_length=50)),
                ('receiveCRCErrors', models.CharField(default='unknown', max_length=50)),
                ('receiveDropped', models.CharField(default='unknown', max_length=50)),
                ('receiveErrors', models.CharField(default='unknown', max_length=50)),
                ('receiveFrameErrors', models.CharField(default='unknown', max_length=50)),
                ('receiveOverrunErrors', models.CharField(default='unknown', max_length=50)),
                ('receivePackets', models.CharField(default='unknown', max_length=50)),
                ('transmitBytes', models.CharField(default='unknown', max_length=50)),
                ('transmitDropped', models.CharField(default='unknown', max_length=50)),
                ('transmitErrors', models.CharField(default='unknown', max_length=50)),
                ('transmitPackets', models.CharField(default='unknown', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OpenFlowSwitch',
            fields=[
                ('dpid', models.CharField(default='unknown', max_length=50, primary_key=True, serialize=False)),
                ('datapathDescription', models.CharField(default='unknown', max_length=50)),
                ('hardwareDescription', models.CharField(default='unknown', max_length=50)),
                ('manufacturerDescription', models.CharField(default='unknown', max_length=50)),
                ('serialNumber', models.CharField(default='unknown', max_length=50)),
                ('softwareDescription', models.CharField(default='unknown', max_length=50)),
                ('version', models.CharField(default='unknown', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OpenFlowTopologyLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(default='unknown', max_length=50)),
                ('src_port', models.CharField(default='unknown', max_length=50)),
                ('src_switch', models.CharField(default='unknown', max_length=50)),
                ('dst_port', models.CharField(default='unknown', max_length=50)),
                ('dst_switch', models.CharField(default='unknown', max_length=50)),
                ('type', models.CharField(default='unknown', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SDNController',
            fields=[
                ('id', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('mgmt_ip', models.CharField(default='unknown', max_length=50)),
                ('mgmt_port', models.CharField(default='unknown', max_length=50)),
                ('status', models.CharField(default='unknown', max_length=50)),
                ('health', models.CharField(default='unknown', max_length=50)),
                ('memory', models.CharField(default='unknown', max_length=50)),
                ('uptime', models.CharField(default='unknown', max_length=50)),
                ('role', models.CharField(default='unknown', max_length=50)),
                ('summary', models.CharField(default='unknown', max_length=50)),
                ('tables', models.CharField(default='unknown', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='openflowtopologylink',
            name='owner_controller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='floodlight.SDNController'),
        ),
        migrations.AddField(
            model_name='openflowswitch',
            name='owner_controller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='floodlight.SDNController'),
        ),
        migrations.AddField(
            model_name='openflowport',
            name='owner_switch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='floodlight.OpenFlowSwitch'),
        ),
        migrations.AddField(
            model_name='openflowentry',
            name='owner_switch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='floodlight.OpenFlowSwitch'),
        ),
    ]
