# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 06:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floodlight', '0005_auto_20160517_0554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sdncontroller',
            name='status',
            field=models.CharField(default='unknown', max_length=200),
        ),
    ]
