# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-09 08:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='end_point',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('alias', models.CharField(default='', max_length=50)),
                ('ip_address', models.GenericIPAddressField(default='')),
                ('port_address', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='vim',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('alias', models.CharField(default='', max_length=50)),
                ('project_domain_id', models.CharField(default='', max_length=50)),
                ('user_domain_id', models.CharField(default='', max_length=50)),
                ('project_name', models.CharField(default='', max_length=50)),
                ('tenant_name', models.CharField(default='', max_length=50)),
                ('username', models.CharField(default='', max_length=50)),
                ('password', models.CharField(default='', max_length=50)),
                ('auth_url', models.CharField(default='', max_length=50)),
                ('image_api_version', models.CharField(choices=[('1.0', '1.0'), ('2.0', '2.0'), ('3.0', '3.0')], max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='end_point',
            name='vim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vim.vim'),
        ),
    ]
