# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-10 04:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vim', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='end_point',
            name='vim',
        ),
        migrations.RemoveField(
            model_name='vim',
            name='image_api_version',
        ),
        migrations.AddField(
            model_name='vim',
            name='version',
            field=models.CharField(choices=[('Kilo', 'Kilo'), ('Liberty', 'Liberty'), ('Mitaka', 'Mitaka')], default='Kilo', max_length=50),
        ),
        migrations.AlterField(
            model_name='vim',
            name='auth_url',
            field=models.CharField(default='http://192.168.43.3:35357/v2.0', max_length=50),
        ),
        migrations.AlterField(
            model_name='vim',
            name='password',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vim',
            name='project_domain_id',
            field=models.CharField(default='default', max_length=50),
        ),
        migrations.AlterField(
            model_name='vim',
            name='project_name',
            field=models.CharField(default='admin', max_length=50),
        ),
        migrations.AlterField(
            model_name='vim',
            name='tenant_name',
            field=models.CharField(default='admin', max_length=50),
        ),
        migrations.AlterField(
            model_name='vim',
            name='user_domain_id',
            field=models.CharField(default='default', max_length=50),
        ),
        migrations.AlterField(
            model_name='vim',
            name='username',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='end_point',
        ),
    ]
