# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-10 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vim', '0002_auto_20160510_0416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vim',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
