# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-10 08:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vim', '0005_auto_20160510_0756'),
    ]

    operations = [
        migrations.CreateModel(
            name='port',
            fields=[
                ('status', models.CharField(default='unknown', max_length=50)),
                ('name', models.CharField(default='unknown', max_length=50)),
                ('allowed_address_pairs', models.CharField(default='unknown', max_length=50)),
                ('admin_state_up', models.CharField(default='unknown', max_length=50)),
                ('network_id', models.CharField(default='unknown', max_length=50)),
                ('tenant_id', models.CharField(default='unknown', max_length=50)),
                ('extra_dhcp_opts', models.CharField(default='unknown', max_length=50)),
                ('mac_address', models.CharField(default='unknown', max_length=50)),
                ('binding_vif_details', models.CharField(default='unknown', max_length=50)),
                ('binding_vif_type', models.CharField(default='unknown', max_length=50)),
                ('device_owner', models.CharField(default='unknown', max_length=50)),
                ('binding_profile', models.CharField(default='unknown', max_length=50)),
                ('port_security_enabled', models.CharField(default='unknown', max_length=50)),
                ('binding', models.CharField(default='unknown', max_length=50)),
                ('fixed_ips', models.CharField(default='unknown', max_length=50)),
                ('id', models.CharField(default='unknown', max_length=50, primary_key=True, serialize=False)),
                ('security_groups', models.CharField(default='unknown', max_length=50)),
                ('device_id', models.CharField(default='unknown', max_length=50)),
                ('parent_vim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vim.vim')),
            ],
        ),
    ]
