# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-10 10:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vim', '0008_auto_20160510_0852'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hypervisor',
            fields=[
                ('id', models.CharField(default='unknown', max_length=50, primary_key=True, serialize=False)),
                ('status', models.CharField(default='unknown', max_length=50)),
                ('service', models.CharField(default='unknown', max_length=50)),
                ('vcpus_used', models.CharField(default='unknown', max_length=50)),
                ('hypervisor_type', models.CharField(default='unknown', max_length=50)),
                ('local_gb_used', models.CharField(default='unknown', max_length=50)),
                ('vcpus', models.CharField(default='unknown', max_length=50)),
                ('hypervisor_hostname', models.CharField(default='unknown', max_length=50)),
                ('memory_mb_used', models.CharField(default='unknown', max_length=50)),
                ('memory_mb', models.CharField(default='unknown', max_length=50)),
                ('current_workload', models.CharField(default='unknown', max_length=50)),
                ('state', models.CharField(default='unknown', max_length=50)),
                ('host_ip', models.CharField(default='unknown', max_length=50)),
                ('cpu_info', models.CharField(default='unknown', max_length=50)),
                ('running_vms', models.CharField(default='unknown', max_length=50)),
                ('free_disk_gb', models.CharField(default='unknown', max_length=50)),
                ('hypervisor_version', models.CharField(default='unknown', max_length=50)),
                ('disk_available_least', models.CharField(default='unknown', max_length=50)),
                ('local_gb', models.CharField(default='unknown', max_length=50)),
                ('free_ram_mb', models.CharField(default='unknown', max_length=50)),
                ('owner_vim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vim.VIM')),
            ],
        ),
        migrations.AlterField(
            model_name='port',
            name='owner_vim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vim.VIM'),
        ),
    ]
