# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-10 11:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vim', '0009_auto_20160510_1049'),
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('status', models.CharField(default='unknown', max_length=50)),
                ('subnets', models.CharField(default='unknown', max_length=50)),
                ('name', models.CharField(default='unknown', max_length=50)),
                ('provider_physical_network', models.CharField(default='unknown', max_length=50)),
                ('router_external', models.CharField(default='unknown', max_length=50)),
                ('tenant_id', models.CharField(default='unknown', max_length=50)),
                ('admin_state_up', models.CharField(default='unknown', max_length=50)),
                ('provider_network_type', models.CharField(default='unknown', max_length=50)),
                ('port_security_enabled', models.CharField(default='unknown', max_length=50)),
                ('shared', models.CharField(default='unknown', max_length=50)),
                ('mtu', models.CharField(default='unknown', max_length=50)),
                ('id', models.CharField(default='unknown', max_length=50, primary_key=True, serialize=False)),
                ('provider_segmentation_id', models.CharField(default='unknown', max_length=50)),
                ('owner_vim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vim.VIM')),
            ],
        ),
        migrations.AlterField(
            model_name='hypervisor',
            name='owner_vim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vim.VIM'),
        ),
        migrations.AlterField(
            model_name='port',
            name='owner_vim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vim.VIM'),
        ),
    ]
