# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-11 04:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vim', '0012_auto_20160510_1138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('addresses', models.CharField(default='unknown', max_length=50)),
                ('created', models.CharField(default='unknown', max_length=50)),
                ('flavor', models.CharField(default='unknown', max_length=50)),
                ('hostId', models.CharField(default='unknown', max_length=50)),
                ('id', models.CharField(default='unknown', max_length=50, primary_key=True, serialize=False)),
                ('image', models.CharField(default='unknown', max_length=50)),
                ('key_name', models.CharField(default='unknown', max_length=50)),
                ('links', models.CharField(default='unknown', max_length=50)),
                ('metadata', models.CharField(default='unknown', max_length=50)),
                ('security_groups', models.CharField(default='unknown', max_length=50)),
                ('status', models.CharField(default='unknown', max_length=50)),
                ('tenant_id', models.CharField(default='unknown', max_length=50)),
                ('updated', models.CharField(default='unknown', max_length=50)),
                ('user_id', models.CharField(default='unknown', max_length=50)),
                ('owner_vim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vim.VIM')),
            ],
        ),
        migrations.AlterField(
            model_name='hypervisor',
            name='owner_vim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vim.VIM'),
        ),
        migrations.AlterField(
            model_name='network',
            name='owner_vim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vim.VIM'),
        ),
        migrations.AlterField(
            model_name='port',
            name='owner_vim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vim.VIM'),
        ),
    ]
