# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-11 04:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vim', '0013_auto_20160511_0411'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('port_state', models.CharField(default='unknown', max_length=50)),
                ('fixed_ips', models.CharField(default='unknown', max_length=50)),
                ('mac_addr', models.CharField(default='unknown', max_length=50)),
                ('net_id', models.CharField(default='unknown', max_length=50)),
                ('port_id', models.CharField(default='unknown', max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='hypervisor',
            name='owner_vim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vim.VIM'),
        ),
        migrations.AlterField(
            model_name='network',
            name='owner_vim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vim.VIM'),
        ),
        migrations.AlterField(
            model_name='port',
            name='owner_vim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vim.VIM'),
        ),
        migrations.AlterField(
            model_name='server',
            name='owner_vim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vim.VIM'),
        ),
        migrations.AddField(
            model_name='interface',
            name='owner_server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vim.Server'),
        ),
    ]
