# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-11 04:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vim', '0018_auto_20160511_0428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interface',
            name='id',
        ),
        migrations.AlterField(
            model_name='hypervisor',
            name='owner_vim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vim.VIM'),
        ),
        migrations.AlterField(
            model_name='interface',
            name='mac_addr',
            field=models.CharField(default='unknown', max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='network',
            name='owner_vim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vim.VIM'),
        ),
        migrations.AlterField(
            model_name='port',
            name='owner_vim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vim.VIM'),
        ),
        migrations.AlterField(
            model_name='server',
            name='owner_vim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vim.VIM'),
        ),
    ]
