# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 05:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vim', '0025_auto_20160512_0517'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('mgmt_ip', models.CharField(default='unknown', max_length=50)),
                ('mgmt_port', models.CharField(default='unknown', max_length=50)),
                ('mgmt_id', models.CharField(default='unknown', max_length=50)),
                ('mgmt_password', models.CharField(default='unknown', max_length=50)),
                ('status', models.CharField(default='unknown', max_length=50)),
                ('hypervisor', models.ForeignKey(default='unknown', on_delete=django.db.models.deletion.CASCADE, to='vim.Hypervisor')),
            ],
        ),
        migrations.CreateModel(
            name='OpenvSwitch',
            fields=[
                ('_uuid', models.CharField(default='unknown', max_length=50, primary_key=True, serialize=False)),
                ('_version', models.CharField(default='unknown', max_length=50)),
                ('bridges', models.CharField(default='unknown', max_length=50)),
                ('cur_cfg', models.CharField(default='unknown', max_length=50)),
                ('db_version', models.CharField(default='unknown', max_length=50)),
                ('external_ids', models.CharField(default='unknown', max_length=50)),
                ('manager_options', models.CharField(default='unknown', max_length=50)),
                ('next_cfg', models.CharField(default='unknown', max_length=50)),
                ('other_config', models.CharField(default='unknown', max_length=50)),
                ('ovs_version', models.CharField(default='unknown', max_length=50)),
                ('ssl', models.CharField(default='unknown', max_length=50)),
                ('statistics', models.CharField(default='unknown', max_length=50)),
                ('system_type', models.CharField(default='unknown', max_length=50)),
                ('system_version', models.CharField(default='unknown', max_length=50)),
                ('owner_Host', models.ForeignKey(default='unknown', on_delete=django.db.models.deletion.CASCADE, to='sdn_switch.Host')),
            ],
        ),
    ]
