# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 05:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdn_switch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Controller',
            fields=[
                ('_uuid', models.CharField(default='unknown', max_length=50, primary_key=True, serialize=False)),
                ('connection_mode', models.CharField(default='unknown', max_length=50)),
                ('controller_burst_limit', models.CharField(default='unknown', max_length=50)),
                ('controller_rate_limit', models.CharField(default='unknown', max_length=50)),
                ('enable_async_messages', models.CharField(default='unknown', max_length=50)),
                ('external_ids', models.CharField(default='unknown', max_length=50)),
                ('inactivity_probe', models.CharField(default='unknown', max_length=50)),
                ('is_connected', models.CharField(default='unknown', max_length=50)),
                ('local_gateway', models.CharField(default='unknown', max_length=50)),
                ('local_ip', models.CharField(default='unknown', max_length=50)),
                ('local_netmask', models.CharField(default='unknown', max_length=50)),
                ('max_backoff', models.CharField(default='unknown', max_length=50)),
                ('other_config', models.CharField(default='unknown', max_length=50)),
                ('role', models.CharField(default='unknown', max_length=50)),
                ('status', models.CharField(default='unknown', max_length=50)),
                ('target', models.CharField(default='unknown', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OVSBridge',
            fields=[
                ('_uuid', models.CharField(default='unknown', max_length=50, primary_key=True, serialize=False)),
                ('controller', models.CharField(default='unknown', max_length=50)),
                ('datapath_id', models.CharField(default='unknown', max_length=50)),
                ('datapath_type', models.CharField(default='unknown', max_length=50)),
                ('external_ids', models.CharField(default='unknown', max_length=50)),
                ('fail_mode', models.CharField(default='unknown', max_length=50)),
                ('flood_vlans', models.CharField(default='unknown', max_length=50)),
                ('flow_tables', models.CharField(default='unknown', max_length=50)),
                ('ipfix', models.CharField(default='unknown', max_length=50)),
                ('mirrors', models.CharField(default='unknown', max_length=50)),
                ('name', models.CharField(default='unknown', max_length=50)),
                ('netflow', models.CharField(default='unknown', max_length=50)),
                ('other_config', models.CharField(default='unknown', max_length=50)),
                ('ports', models.CharField(default='unknown', max_length=50)),
                ('protocols', models.CharField(default='unknown', max_length=50)),
                ('sflow', models.CharField(default='unknown', max_length=50)),
                ('status', models.CharField(default='unknown', max_length=50)),
                ('stp_enable', models.CharField(default='unknown', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OVSInterface',
            fields=[
                ('_uuid', models.CharField(default='unknown', max_length=50, primary_key=True, serialize=False)),
                ('admin_state', models.CharField(default='unknown', max_length=50)),
                ('bfd', models.CharField(default='unknown', max_length=50)),
                ('bfd_status', models.CharField(default='unknown', max_length=50)),
                ('cfm_fault', models.CharField(default='unknown', max_length=50)),
                ('cfm_fault_status', models.CharField(default='unknown', max_length=50)),
                ('cfm_flap_count', models.CharField(default='unknown', max_length=50)),
                ('cfm_health', models.CharField(default='unknown', max_length=50)),
                ('cfm_mpid', models.CharField(default='unknown', max_length=50)),
                ('cfm_remote_mpids', models.CharField(default='unknown', max_length=50)),
                ('cfm_remote_opstate', models.CharField(default='unknown', max_length=50)),
                ('duplex', models.CharField(default='unknown', max_length=50)),
                ('external_ids', models.CharField(default='unknown', max_length=50)),
                ('link_speed', models.CharField(default='unknown', max_length=50)),
                ('link_state', models.CharField(default='unknown', max_length=50)),
                ('mac', models.CharField(default='unknown', max_length=50)),
                ('mac_in_use', models.CharField(default='unknown', max_length=50)),
                ('mtu', models.CharField(default='unknown', max_length=50)),
                ('name', models.CharField(default='unknown', max_length=50)),
                ('ofport', models.CharField(default='unknown', max_length=50)),
                ('ofport_request', models.CharField(default='unknown', max_length=50)),
                ('options', models.CharField(default='unknown', max_length=50)),
                ('other_config', models.CharField(default='unknown', max_length=50)),
                ('statistics', models.CharField(default='unknown', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OVSPort',
            fields=[
                ('_uuid', models.CharField(default='unknown', max_length=50, primary_key=True, serialize=False)),
                ('bond_active_slave', models.CharField(default='unknown', max_length=50)),
                ('bond_downdelay', models.CharField(default='unknown', max_length=50)),
                ('bond_fake_iface', models.CharField(default='unknown', max_length=50)),
                ('bond_mode', models.CharField(default='unknown', max_length=50)),
                ('bond_updelay', models.CharField(default='unknown', max_length=50)),
                ('external_ids', models.CharField(default='unknown', max_length=50)),
                ('fake_bridge', models.CharField(default='unknown', max_length=50)),
                ('interfaces', models.CharField(default='unknown', max_length=50)),
                ('lacp', models.CharField(default='unknown', max_length=50)),
                ('mac', models.CharField(default='unknown', max_length=50)),
                ('name', models.CharField(default='unknown', max_length=50)),
                ('other_config', models.CharField(default='unknown', max_length=50)),
                ('qos', models.CharField(default='unknown', max_length=50)),
                ('statistics', models.CharField(default='unknown', max_length=50)),
                ('status', models.CharField(default='unknown', max_length=50)),
                ('tag', models.CharField(default='unknown', max_length=50)),
                ('trunks', models.CharField(default='unknown', max_length=50)),
                ('vlan_mode', models.CharField(default='unknown', max_length=50)),
            ],
        ),
    ]
