# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 01:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openvswitch', '0005_auto_20160518_0139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ovsport',
            name='owner_Bridge',
        ),
    ]
