# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 01:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openvswitch', '0006_remove_ovsport_owner_bridge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ovsbridge',
            name='ports',
            field=models.CharField(default='unknown', max_length=200),
        ),
    ]
