# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 02:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openvswitch', '0007_auto_20160518_0154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ovscontroller',
            name='owner_controller',
        ),
        migrations.AddField(
            model_name='ovscontroller',
            name='version',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='openvswitch',
            name='bridges',
            field=models.CharField(default='unknown', max_length=200),
        ),
    ]
