# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 02:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openvswitch', '0008_auto_20160518_0235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ovscontroller',
            old_name='version',
            new_name='_version',
        ),
    ]
