# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-24 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openvswitch', '0009_auto_20160518_0236'),
    ]

    operations = [
        migrations.AddField(
            model_name='ovsinterface',
            name='attached_mac',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='ovsinterface',
            name='iface_id',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='ovsinterface',
            name='iface_status',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='ovsinterface',
            name='vm_uuid',
            field=models.CharField(default='unknown', max_length=50),
        ),
    ]
