# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-16 08:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlowClassifier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField()),
                ('name', models.CharField(default='', max_length=50)),
                ('description', models.CharField(default=None, max_length=50)),
                ('ethertype', models.CharField(default=None, max_length=50)),
                ('protocol', models.CharField(default=None, max_length=50)),
                ('source_port_range_min', models.CharField(default=None, max_length=50)),
                ('source_port_range_max', models.CharField(default=None, max_length=50)),
                ('destination_port_range_min', models.CharField(default=None, max_length=50)),
                ('destination_port_range_max', models.CharField(default=None, max_length=50)),
                ('source_ip_prefix', models.CharField(default=None, max_length=50)),
                ('destination_ip_prefix', models.CharField(default=None, max_length=50)),
                ('logical_source_port', models.UUIDField(blank=True, null=True)),
                ('logical_destination_port', models.UUIDField(blank=True, null=True)),
                ('l7_parameters', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceFunction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField()),
                ('name', models.CharField(default='', max_length=50)),
                ('description', models.CharField(default='', max_length=50)),
                ('ingress', models.UUIDField()),
                ('egress', models.UUIDField()),
                ('service_function_parameters', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceFunctionChain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField()),
                ('name', models.CharField(default='', max_length=50)),
                ('description', models.CharField(default='', max_length=50)),
                ('flow_classifiers', models.CharField(default='', max_length=200)),
                ('chain_parameters', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceFunctionGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField()),
                ('name', models.CharField(default='', max_length=50)),
                ('description', models.CharField(default='', max_length=50)),
                ('service_function_chain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_function_groups', to='sfc.ServiceFunctionChain')),
            ],
        ),
        migrations.AddField(
            model_name='servicefunction',
            name='Service_function_groups',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_functions', to='sfc.ServiceFunctionGroup'),
        ),
    ]
