# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-04 09:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('IP', models.CharField(max_length=50)),
                ('MAC', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SF',
            fields=[
                ('device_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('mgmtIP', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SFF',
            fields=[
                ('device_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('mgmtIP', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='sf',
            name='connected_sff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sfc.SFF'),
        ),
        migrations.AddField(
            model_name='interface',
            name='device_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sfc.SF'),
        ),
    ]
