# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-04 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sff',
            name='device_id',
        ),
        migrations.AlterField(
            model_name='sff',
            name='name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
