# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-09 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data_plane_locator',
            name='name',
        ),
        migrations.RemoveField(
            model_name='rendered_service_path',
            name='name',
        ),
        migrations.RemoveField(
            model_name='service_function',
            name='name',
        ),
        migrations.RemoveField(
            model_name='service_function_chain',
            name='name',
        ),
        migrations.RemoveField(
            model_name='service_function_forwarder',
            name='name',
        ),
        migrations.RemoveField(
            model_name='service_function_locator',
            name='name',
        ),
        migrations.AddField(
            model_name='rendered_service_path',
            name='alias',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='service_function',
            name='alias',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='service_function_chain',
            name='alias',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='service_function_forwarder',
            name='alias',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='data_plane_locator',
            name='ip_mgmt_address',
            field=models.GenericIPAddressField(default=''),
        ),
        migrations.AlterField(
            model_name='data_plane_locator',
            name='mac',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='rendered_service_path',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='service_function',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='service_function',
            name='ip_mgmt_address',
            field=models.GenericIPAddressField(default=''),
        ),
        migrations.AlterField(
            model_name='service_function_chain',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='service_function_forwarder',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='service_function_forwarder',
            name='ip_mgmt_address',
            field=models.GenericIPAddressField(default=''),
        ),
    ]
