# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-16 08:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sfc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowclassifier',
            name='service_function_chain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flow_classifier', to='sfc.ServiceFunctionChain'),
        ),
    ]
