# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-16 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfc', '0002_flowclassifier_service_function_chain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicefunctionchain',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='servicefunctionchain',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
