# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-16 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfc', '0003_auto_20160616_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowclassifier',
            name='description',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='flowclassifier',
            name='destination_ip_prefix',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='flowclassifier',
            name='destination_port_range_max',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='flowclassifier',
            name='destination_port_range_min',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='flowclassifier',
            name='ethertype',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='flowclassifier',
            name='protocol',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='flowclassifier',
            name='source_ip_prefix',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='flowclassifier',
            name='source_port_range_max',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='flowclassifier',
            name='source_port_range_min',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
