# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-24 05:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfc', '0004_auto_20160616_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicefunctionchain',
            name='active',
            field=models.CharField(choices=[('inactive', 'inactive'), ('active', 'active')], default='inactive', max_length=50),
        ),
    ]
