# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 00:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('addreq', models.CharField(default='', max_length=50)),
                ('curalarmseq', models.CharField(default='', max_length=50, primary_key=True, serialize=False)),
                ('orgnamescode', models.CharField(default='', max_length=50)),
                ('serveruuid', models.CharField(default='', max_length=50)),
                ('monitemistancesq', models.CharField(default='', max_length=50)),
                ('perceive_user', models.CharField(default='', max_length=50)),
                ('resolve_user', models.CharField(default='', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
